### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dany-LF** [triedgriefdev/mcdown#1]
Running...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "mcdown.py", line 29, in connectize
    addr[0], int(addr[1]), username=uname(random.randint(6, 9)))
IndexError: list index out of range

**Comment by triedgriefdev** [comment]
You must provide arguments
python3 mcdown.py ip port

**Comment by triedgriefdev** [comment]
most importantly, mcdown is no supported longer
